<template>
  <div>
    <div id="previewbtns" style="display: none">
    </div>
    <input type="hidden" id="lease">
    <input type="hidden" id="leaseAddendum">
    <div
        class="modal fade unit-modal"
        id="document_preview"
        tabindex="-1"
        aria-labelledby="document_preview"
        aria-hidden="true"
    >
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header border-0" v-if="this.unit">
            Document Preview
            <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
            ></button>
          </div>
          <div class="modal-body text-start">
            <button class="btn btn-primary mr-10" id="btn-preview-lease" @click="showPreview('lease')">Preview Lease
            </button>
            <button class="btn btn-primary" id="btn-preview-lease-addendum" onc @click="showPreview('leaseAddendum')">
              Preview Urban Sky Addendum
            </button>
            <div id="document_preview_div mt-10" style="margin-top: 10px;border: 1px solid">
              <iframe height="550px" width="100%" id="document_preview_iframe" src=""></iframe>
            </div>
            <div class="row mt-10">
              <div class="col-md-3">
                <div class="dropdown-wrapper">
                  <label class="dropdown-label text-capitalize">Select The Term Length(In Month)</label>
                  <multiselect 
                  :selectLabel="''"
                  :deselectLabel= "''"
                      v-model="term"
                      tag-placeholder="Add this as new tag"
                      placeholder=""
                      label="id"
                      track-by="id"
                      :options="termOptions"
                      :multiple="false"
                  ></multiselect>
                </div>
              </div>
              <div class="col-md-3">
                <input type="checkbox" @click="termSelected()" v-model="termConfirmed" id="confirm-term"
                       value="1"
                       style="margin-left: 5px">
                Confirm the term length
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button
                title="To edit the contents of these documents, go to documents / manage documents  / lease Packet"
                :disabled="this.term===null || this.termConfirmed === false"
                @click="sendEmails()" class="btn bkg-primary mr-10">Submit
            </button>
            <button
                @click="cancel()"
                class="btn bkg-danger">Cancel
            </button>
          </div>
        </div>
      </div>
    </div>

  </div>
</template>

<script>
import {config} from "../../config";
export default {
  data() {
    return {
      unit: null,
      signDocs: null,
      term: null,
      termConfirmed: false,
      disableSubmit: true,
      termOptions: [],
    };
  },
  created() {
    for (let count = 1; count < 121; count++) {
      this.termOptions.push({"id": count});
    }
  },
  methods: {
    termSelected() {
    },
    sendOnboarding(unit) {
      this.unit = unit;
      Swal.fire({
        title: config.confirmBoxTitle,
        text: 'When a new guarantor and/or CoGuarantor are created, respective residents will be prompted to sign 2 documents (a) the "Lease"-generated by management and (b) the "Urban Sky addendum"-generated automatically).',
        icon: "warning",
        showCancelButton: true,
        confirmButtonColor: config.confirmButtonColor,
        cancelButtonColor: config.cancelButtonColor,
        confirmButtonText: config.confirmButtonText,
      }).then((result) => {
        if (result.value) {
          let params = {
            unitId: unit.id,
          };
          this.showLoader();
          this.$http
              .post("/startonboardingprocess", params)
              .then((response) => {
                response = response.data;
                response = JSON.parse(response)
                if (response.status) {
                  $('#previewbtns').show();
                  $('#lease').val(response.message['Sign Lease']);
                  $('#leaseAddendum').val(response.message['Sign Addendum']);
                  $('#btn-preview-lease').click();
                  $('#document_preview').modal('toggle');
                  this.signDocs = [response.message['Sign Lease'], response.message['Sign Addendum']];
                } else {
                  Toast.fire({
                    icon: "error",
                    position: "top",
                    title: response.message ?? "Something went wrong",
                  });
                }
                this.removeLoader();
              })
              .catch((error) => {
                this.removeLoader();
                console.error(error);
              });
        }
      });
    },
    sendEmails() {
      this.showLoader();
      let params = {signDocs: this.signDocs, term: this.term.id};
      this.$http
          .post("/sendDocumentEmails", params)
          .then((response) => {
            response = response.data;
            if (response.status) {
              $('#document_preview').modal('hide');
              let docResponse = response.response;
              docResponse = JSON.parse(docResponse);
              if (docResponse.status) {
                Toast.fire({
                  icon: "success",
                  position: "top",
                  title: "You successfully sent an invitation to sign the Lease and Urban Sky addendum.",
                });
                this.$parent.loadData();
              } else
                Toast.fire({
                  icon: "error",
                  position: "top",
                  title: "Failed. Something went wrong with the document sending.",
                });
            } else {
              Toast.fire({
                icon: "error",
                position: "top",
                title: response.message ?? "Something went wrong",
              });
            }
            this.removeLoader();
          })
          .catch((error) => {
            $('#document_preview').modal('toggle');
            this.removeLoader();
          });
    },
    cancel() {
      this.showLoader();
      let params = {signDocs: this.signDocs, term: this.term.id};
      this.$http
          .post("/cancelOnboardingDocument", params)
          .then((response) => {
            response = response.data;
            if (response.status) {
              $('#document_preview').modal('hide');
              Toast.fire({
                icon: "success",
                position: "top",
                title: "Documents were cancelled successfully",
              });
            } else {
              Toast.fire({
                icon: "error",
                position: "top",
                title: response.message ?? "Something went wrong",
              });
            }
            this.removeLoader();
          })
          .catch((error) => {
            $('#document_preview').modal('toggle');
            this.removeLoader();
          });
    },
    showPreview(type) {
      this.showLoader();
      let docId = $('#' + type).val();
      this.$http
          .get("/getDocumentPreview/" + docId)
          .then((response) => {
            response = response.data;
            if (response.status) {
              $('#document_preview_iframe').attr('src', response.url);
            } else {
              Toast.fire({
                icon: "error",
                position: "top",
                title: response.message ?? "Something went wrong",
              });
            }
            this.removeLoader();
          })
          .catch((error) => {
            this.removeLoader();
            console.error(error);
          });
    }
  },
};
</script>
